// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	entities "go-carbon-tracker/entities"

	mock "github.com/stretchr/testify/mock"
)

// TripRepository is an autogenerated mock type for the TripRepository type
type TripRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *TripRepository) Create(_a0 entities.Trip) (entities.Trip, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entities.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Trip) (entities.Trip, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(entities.Trip) entities.Trip); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(entities.Trip)
	}

	if rf, ok := ret.Get(1).(func(entities.Trip) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *TripRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: filter
func (_m *TripRepository) GetAll(filter entities.Filter) ([]entities.Trip, entities.Pagination, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.Trip
	var r1 entities.Pagination
	var r2 error
	if rf, ok := ret.Get(0).(func(entities.Filter) ([]entities.Trip, entities.Pagination, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(entities.Filter) []entities.Trip); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.Filter) entities.Pagination); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(entities.Pagination)
	}

	if rf, ok := ret.Get(2).(func(entities.Filter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *TripRepository) GetByID(id string) (entities.Trip, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.Trip, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.Trip); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Trip)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *TripRepository) Update(_a0 entities.Trip) (entities.Trip, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entities.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Trip) (entities.Trip, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(entities.Trip) entities.Trip); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(entities.Trip)
	}

	if rf, ok := ret.Get(1).(func(entities.Trip) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTripRepository creates a new instance of TripRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTripRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TripRepository {
	mock := &TripRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
